### ISSUE TITLE
p5.js Version

### ISSUE THREAD

**Issue by crhallberg** [jeffThompson/CollisionDetection#5] opened 2018-10-02 19:31 UTC
Hello! For my class (which I teach in Javascript) I converted all of the examples to Javascript. To do so, I also made some *major* changes to the way things are compiled and organized. 

If there is a way to reconcile these code bases, I'd be happy to help but in the meantime, I just wanted to make you aware of this fork: https://github.com/crhallberg/CollisionDetection.

Website: https://crhallberg.com/CollisionDetection/Website/

**Comment by crhallberg** [comment] 2018-10-03 15:11
Sorry, I meant to link to the particular branch: https://github.com/crhallberg/CollisionDetection/tree/p5js.

I teach a class at TCNJ called Intro to Interactive Multimedia. It's for the Interactive Multimedia major but I see many different majors coming in. It's a popular "let's try coding" class on campus.

I think the biggest change I made from the main branch is using the actual example code in the Markdown. I'm not sure how you were building the original site's PHP, but I added a node.js script to build the page in HTML from the Markdown.

**Comment by GoToLoop** [comment] 2018-10-03 15:39
Processing sketches are very OOP.
So no matter which current flavor language p5 is under, OOP should be prioritized IMO.
Also JS got everything needed for OOP via the `class` keyword: ;-)
https://Developer.Mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor

**Comment by crhallberg** [comment] 2018-10-03 16:29
I did eventually [decide on `class`](https://github.com/crhallberg/CollisionDetection/blob/p5js/MarkdownFiles/object_oriented_collision.md) but I wasn't sure if I should use that or anonymous object due to ease and browser support.

**Comment by GoToLoop** [comment] 2018-10-03 17:32
- There are many bugs on that link though. =(
- You're forgetting to use `this.` a lot there!
- Any member of a class in JS needs to be prefixed w/ `this.` if it's not using 1 already.

**Comment by jeffThompson** [comment] 2018-10-03 18:29
I'm going to close this, since the issue is a notification about the fork (thanks again).

Chris – if you have any other thoughts on how you re-organized my code, feel free to reopen and add them here!

**Closed by jeffThompson** 2018-10-03 18:29 UTC

**Comment by crhallberg** [comment] 2018-10-03 18:44
@jeffThompson Thank you!

@GoToLoop Browser compatibility has finally caught up (I've been picking at this for a while). [The code seems to be working just fine](https://crhallberg.com/CollisionDetection/Website/object_oriented_collision.html), but if you want to open a pull request or suggest issues on [my fork](https://github.com/crhallberg/CollisionDetection/tree/p5js), we should improve this tool! I don't want bugs or bad form in my teaching tools.

**Comment by GoToLoop** [comment] 2018-10-03 21:19
Unfortunately your fork doesn't have an "Issues" section; just "Pull Requests".
Sorry to use this space for posting a bug report for the fork. =(

The `<script>` sketch from https://GitHub.com/crhallberg/CollisionDetection/blob/p5js/Website/object_oriented_collision.html is correct.
But somehow, the displayed code in the site doesn't match the actual running code:
https://CrHallberg.com/CollisionDetection/Website/object_oriented_collision.html

B/c `this.` is missing in many places. For example inside method _**Rectangle**_::**display()**:
```js
    display() {
        if (this.hit) fill(255, 150, 0);
        else fill(0, 150, 255);
        noStroke();
        rect(x, y, w, h);
    }
```
Clearly `rect(x, y, w, h);` should be `rect(this.x, this.y, this.w, this.h);` instead!

**Comment by jeffThompson** [comment] 2018-10-04 07:08
Ok, I'm going to ask you guys to take this to email then. These aren't issues related to this main branch, and I get an email notification every time someone posts to this thread :)
